GET http://localhost:8000/


###create new user

POST  http://localhost:8000/api/v1/user/
Content-Type: application/json

{
    "fname": "Divyesh",
    "lname": "Shrestha",
    "email": "111@gmail.com",
    "dob": "1995/2/10",
    "password": "123456",
    "phone": "123456",
    "address": "Sydney, NSW",
    "gender": "male"
   
}

##### Email APIs

### verify admin email

PATCH  http://localhost:3000/email-verification
Content-Type: application/ application/json

{
    "pin": "517796",
    "email": "bssss@gmail.com"
}

//send email confirmation and validate email
//account has been activated


###  user forget password otp request
POST  http://localhost:8000/api/v1/user/request-otp
Content-Type: application/json

{
    "email": "bssss@gmail.com",
    "password": "123456gdg"
}
### Logout user
POST  http://localhost:8000/api/v1/user/logout
Content-Type:  application/json

{
    "accessJWT": "",
    "resfreshJWT': "",
}

### admin update password
POST  http://localhost:8000/api/v1/user/password-update
Content-Type: application/json
Authorization:

{
    "currentPassword": "",
    "confirmPassword": ""
}
### reset new password
POST  http://localhost:8000/api/v1/user/reset-password
Content-Type: application/json
Authorization:

{
     "otp": 25545, 
    "newPassword": "123456",
 
}


##################category router

### get all or single categories
GET  http://localhost:8000/api/v1/category/

### get single category
GET  http://localhost:8000/api/v1/category/61451ac546a24caca0ca8853


###Post new category

POST http://localhost:8000/api/v1/category/
Content-Type:  application/json

{
    "name": "Home and garden",
    "parentCat": null
}

### update category

PATCH http://localhost:8000/api/v1/category/
Content-Type:  application/json
{
    "_id": "furniture",
    "name": ,
    "parenCat": null
}


### Delete categories

DELETE   http://localhost:8000/api/v1/category/61451ac546a24caca0ca8853


####Token routes

### get new accessrefresh token
GET http://localhost:8000/api/v1/token

Authorization: 



###############token routers

###get new accessrefresh token
GET http://localhost:8000/api/v1/token
Authorization:

### Login user
POST  http://localhost:8000/api/v1/token/login
Content-Type: application/json

{
    "email": "bssss@gmail.com",
    
}





